FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install
RUN npm install --save-dev @testing-library/react @testing-library/jest-dom jest

# Copy project files
COPY . .

# Set environment variables
ENV CI=true
ENV REACT_APP_API_URL=http://localhost:8000/api

# Command to run tests
CMD ["npm", "test", "--", "--watchAll=false"] 