version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=1
      - SECRET_KEY=django-insecure-test-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    command: npm start -- --host 0.0.0.0

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=1
      - SECRET_KEY=django-insecure-test-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - PYTHONPATH=/app:.
    depends_on:
      - backend

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CI=true
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  e2e-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CYPRESS_BASE_URL=http://frontend:3000
      - REACT_APP_API_URL=http://backend:8000/api
    command: npx cypress run
    depends_on:
      - frontend
      - backend

volumes:
  media_data: 