[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://file-vault-cicd.netlify.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 