name: Backend Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          python manage.py test

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 65.2.168.38
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/*"
          target: "/home/ec2-user/backend"
          strip_components: 1

      - name: Restart Backend Service
        uses: appleboy/ssh-action@master
        with:
          host: 65.2.168.38
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/backend
            docker-compose down
            docker-compose up -d --build 
